### ISSUE TITLE
When a video is playing and you open the control center or coversheet, the video goes PIP and goes in back of the control center/coversheet

### ISSUE THREAD

**Issue by mattp12** [SpicaT/YouPIP#1]
https://media.giphy.com/media/Bp2Vut5eFnpQJmdykK/giphy.mp4

**Comment by SpicaT** [comment]
When Control Center is being pulled, the app will resign active. YouTube app implements PIP to be activated when the app resigns active. I may or may not be able to “mitigate” this issue, though.

**Comment by mattp12** [comment]
Okay :)
