### ISSUE TITLE
Takes 2 tries  

### ISSUE THREAD

**Issue by Sohailwahab** [SpicaT/YouPIP#2]
Why won’t it just detach the video on the first attempt. It takes me 2 tries to get the video to PIP. once detached and disappears. Second time, after letting it to load for minutes and then I’m able to get the video working on PIP. please make it work flawlessly on the first attempt. I was thinking it would work flawlessly when I installed it the first time.

**Comment by SpicaT** [comment]
This is a known issue, but uncertain whether to be of YouTube app itself or the tweak that overlooked anything.

**Comment by Sohailwahab** [comment]
Putting a button/Activator action option for pip instead of the home gesture might fix this issue.
